spring:
  application:
    name: api-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

eureka:
  client:
    fetch-registry: true 
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 9898
  servlet:
    context-path: /api-auth
  forward-headers-strategy: FRAMEWORK
    
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 3600000 # 1 hora
      refresh-token:
        expiration: 3600000 # 8 horas

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  file:
    name: ./logs/log-file-api-auth.log

nome:
  sistema: Base

url:
  redirect:
    sucess: http://localhost:8080/projeta-gestor/


  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/