spring:
  application:
    name: projeta

server:
  port: 3001
  servlet:
    context-path: /projeta

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  #   instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}  
feign:
  client:
    url:
      api-auth: http://localhost:8080/auth/
#Configuração actuator    
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file-site.log


projeta:
  url:
    login: http://localhost:8080/api-auth/api-auth/login

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
