spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      # API-AUTH =====================================
       - id: api-auth-abertos
         uri: lb://api-auth
         predicates:
           - Path=/api-auth/api-auth/login
           - Path=/api-auth/api-auth/auth/**

       - id: api-auth-fechados
         uri: lb://api-auth
         predicates:
           - Path=/api-auth/api-auth/dominios/**
           - Path=/api-auth/api-auth/users/**
         filters:
           - AuthenticationFilter
      # SITE =====================================
       - id: site-auth-abertos
         uri: lb://site
         predicates:
           - Path=/projeta/css/**
      # API-FRONT =====================================
       - id: front-api
         uri: lb://front-api
         predicates:
           - Path=/**
      # ============================================
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    fetch-registry: true 
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
client:
  urlapi-auth: http://localhost:8080/auth